return {
	"AstroNvim/astrocommunity",

	{ import = "astrocommunity.color.modes-nvim" },
	{ import = "astrocommunity.color.twilight-nvim" },
  { import = "astrocommunity.colorscheme.catppuccin" },
	{ import = "astrocommunity.completion.codeium-vim" },
	{ import = "astrocommunity.diagnostics.lsp_lines-nvim" },
	{ import = "astrocommunity.diagnostics.trouble-nvim" },
	{ import = "astrocommunity.editing-support.zen-mode-nvim" },
	{ import = "astrocommunity.git.openingh-nvim" },
	{ import = "astrocommunity.media.vim-wakatime" },
	{ import = "astrocommunity.pack.astro" },
	{ import = "astrocommunity.pack.bash" },
	{ import = "astrocommunity.pack.html-css" },
	{ import = "astrocommunity.pack.json" },
	{ import = "astrocommunity.pack.lua" },
	{ import = "astrocommunity.pack.markdown" },
	{ import = "astrocommunity.pack.prisma" },
	{ import = "astrocommunity.pack.python" },
	{ import = "astrocommunity.pack.tailwindcss" },
	{ import = "astrocommunity.pack.typescript" },
	{ import = "astrocommunity.scrolling.nvim-scrollbar" },
}
